title: Manoa ICStudy
description: Study Buddy, Application, and Interests for the UH Community
google_analytics:
theme: jekyll-theme-architect
github:
  is_project_page: true
  repository_url: https://github.com/manoa-icstudy/manoa-icstudy.github.io
  is_user_page: true
  owner_url: https://manoa-icstudy.site/
plugins:
  - jekyll-mentions
