title: Manoa ICStudy
description: Study Buddy, Application, and Interests for the UH Community
google_analytics:
theme: jekyll-theme-architect
github:
  owner_url: https://github.com/manoa-icstudy/manoa-icstudy.github.io
plugins:
  - jekyll-mentions
