title: Manoa ICStudy
description: Study Buddy, Application, and Interests for the UH Community
github:
  repository_url: https://github.com/manoa-icstudy/manoa-icstudy.github.io
google_analytics:
theme: jekyll-theme-architect
plugins:
  - jekyll-mentions
