title: BowFolios
description: Study Buddy, Projects, and Interests for the UH Community
google_analytics:
show_downloads: false
theme: jekyll-theme-architect
github:
  is_project_page: true
  repository_url: https://github.com/manoa-icstudy/manoa-icstudy.github.io
gems:
  - jekyll-mentions
