title: Manoa ICStudy
description: Study Buddy, Application, and Interests for the UH Community
github:
  is_project_page: true
  repository_url: https://github.com/manoa-icstudy/manoa-icstudy.github.io
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
plugins:
  - jekyll-mentions
